Repository BedalFriend/BaedalFriend-FE, pull requests merged in 2022-11, with the labels that each got.

#7 카카오 소셜 로그인, 헤더 / gnb
  .gitignore
  package.json
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/offline.html
  public/pwabuilder-sw.js
  src/components/elements/timer/Timer.jsx
  src/components/elements/timer/TimerStyle.jsx
  src/components/layout/Layout.jsx
  src/components/layout/LayoutStyle.jsx
  src/components/layout/gnbFloat/GnbFloat.jsx
  src/components/layout/gnbFloat/GnbFloatStyle.jsx
  src/components/layout/header/Header.jsx
  src/components/layout/header/HeaderStyle.jsx
  src/context/SocketContext.jsx
  src/context/TabContext.jsx
  src/imgs/kakao_login/en/kakao_login_large_narrow.png
  src/imgs/kakao_login/en/kakao_login_large_wide.png
  src/imgs/kakao_login/en/kakao_login_medium_narrow.png
  src/imgs/kakao_login/en/kakao_login_medium_wide.png
  src/imgs/kakao_login/kakao_login_original.psd
  src/imgs/kakao_login/ko/kakao_login_large_narrow.png
  src/imgs/kakao_login/ko/kakao_login_large_wide.png
  src/imgs/kakao_login/ko/kakao_login_medium_narrow.png
  src/imgs/kakao_login/ko/kakao_login_medium_wide.png
  src/index.css
  src/index.js
  src/pages/KakaoLoginPage.jsx
  src/pages/TestPage.jsx
  src/pages/main/MainPage.jsx
  src/pages/main/MainPageStyle.jsx
  src/redux/modules/UserSlice.js
  src/shared/api/KakaoRequest.js
  src/shared/api/Request.js
  src/shared/api/Users.js
  src/shared/router/Router.js
  src/styles/GlobalStyle.jsx
  src/styles/fonts/pretendard-1.3.6/woff-subset/Pretendard-Black.subset.woff
  src/styles/fonts/pretendard-1.3.6/woff-subset/Pretendard-Bold.subset.woff
  src/styles/fonts/pretendard-1.3.6/woff-subset/Pretendard-ExtraBold.subset.woff
  src/styles/fonts/pretendard-1.3.6/woff-subset/Pretendard-ExtraLight.subset.woff
  src/styles/fonts/pretendard-1.3.6/woff-subset/Pretendard-Light.subset.woff
  src/styles/fonts/pretendard-1.3.6/woff-subset/Pretendard-Medium.subset.woff
  src/styles/fonts/pretendard-1.3.6/woff-subset/Pretendard-Regular.subset.woff
  src/styles/fonts/pretendard-1.3.6/woff-subset/Pretendard-SemiBold.subset.woff
  src/styles/fonts/pretendard-1.3.6/woff-subset/Pretendard-Thin.subset.woff
  src/styles/fonts/pretendard-1.3.6/woff2-subset/Pretendard-Black.subset.woff2
  src/styles/fonts/pretendard-1.3.6/woff2-subset/Pretendard-Bold.subset.woff2
  src/styles/fonts/pretendard-1.3.6/woff2-subset/Pretendard-ExtraBold.subset.woff2
  src/styles/fonts/pretendard-1.3.6/woff2-subset/Pretendard-ExtraLight.subset.woff2
  src/styles/fonts/pretendard-1.3.6/woff2-subset/Pretendard-Light.subset.woff2
  src/styles/fonts/pretendard-1.3.6/woff2-subset/Pretendard-Medium.subset.woff2
  src/styles/fonts/pretendard-1.3.6/woff2-subset/Pretendard-Regular.subset.woff2
  src/styles/fonts/pretendard-1.3.6/woff2-subset/Pretendard-SemiBold.subset.woff2
  src/styles/fonts/pretendard-1.3.6/woff2-subset/Pretendard-Thin.subset.woff2
  yarn.lock
Labels: feat/account

#16 Feat/chat
  public/Property-1_Default.ico
  public/Property-1_Secondary.ico
  public/favicon.ico
  public/index.html
  public/logo1024.png
  public/manifest.json
  src/components/elements/card/Card.jsx
  src/components/elements/card/CardStyle.jsx
  src/components/elements/profilePic/ProfilePic.jsx
  src/components/elements/profilePic/ProfilePicStyle.jsx
  src/components/elements/timer/TimerStyle.jsx
  src/components/layout/LayoutStyle.jsx
  src/components/layout/header/Header.jsx
  src/components/layout/header/HeaderStyle.jsx
  src/imgs/BasicProfile.png
  src/index.js
  src/pages/main/MainPage.jsx
  src/pages/main/MainPageStyle.jsx
  src/styles/GlobalStyle.jsx
Labels: Design, feat/chat

#30 Feat/post
  public/index.html
  src/components/layout/gnbFloat/GnbFloat.jsx
  src/imgs/upload/AllMenu.png
  src/imgs/upload/Arrived.png
  src/imgs/upload/DropdownList 2.png
  src/imgs/upload/DropdownList.png
  src/imgs/upload/Frame 48.png
  src/imgs/upload/Map_Marker.png
  src/imgs/upload/MeetingLoca.png
  src/imgs/upload/Orange_Map_Marker.png
  src/imgs/upload/Party.png
  src/imgs/upload/Payment.png
  src/imgs/upload/Time.png
  src/imgs/upload/search.png
  src/pages/DetailPage.jsx
  src/pages/TestPage.jsx
  src/pages/upload/UploadPage.jsx
  src/pages/upload/UploadPageStyle.jsx
  src/pages/upload/upload/UploadCategory.jsx
  src/pages/upload/upload/searchPartyMap/SearchPartyMap.jsx
  src/pages/upload/upload/searchStoreMap/SearchStoreMap.jsx
  src/pages/upload/upload/uploadStepOne/UploadStepOne.jsx
  src/pages/upload/upload/uploadStepTwo/UploadStepTwo.jsx
  src/pages/upload/upload/uploadStepTwo/currentLocation/CurrentLocation.jsx
  src/pages/upload/upload/uploadStepTwo/select/Select.jsx
  src/pages/upload/upload/uploadStepTwo/toggle/Toggle.jsx
  src/redux/config/ConfigStore.js
  src/redux/modules/PostSlice.js
  src/shared/router/Router.js
Labels: documentation

#32 feat: select 기능 구현
  src/components/select/Select.jsx
  src/pages/upload/upload/uploadStepTwo/UploadStepTwo.jsx
  src/pages/upload/upload/uploadStepTwo/select/Select.jsx
Labels: enhancement

#33 feat : selectStyle 추가
  src/pages/upload/UploadPageStyle.jsx
Labels: enhancement

#34 fix: select 기능 수정
  src/components/select/Select.jsx
  src/pages/upload/UploadPage.jsx
  src/pages/upload/UploadPageStyle.jsx
  src/pages/upload/upload/uploadStepOne/UploadStepOne.jsx
  src/pages/upload/upload/uploadStepTwo/UploadStepTwo.jsx
  src/shared/router/Router.js
Labels: enhancement

#37 Feat/search/기본검색
  src/hooks/useOutSideClick.js
  src/pages/main/MainPage.jsx
  src/pages/main/MainPageStyle.jsx
  src/pages/search/RecentWord.jsx
  src/pages/search/RecentWordStyle.jsx
  src/pages/search/SearchModal.jsx
  src/pages/search/SearchModalStyle.jsx
  src/pages/search/SearchPage.jsx
  src/pages/search/SearchPageStyle.jsx
  src/redux/modules/PostSlice.js
  src/shared/router/Router.js
Labels: enhancement

#45 Feat/search/카테고리검색
  src/pages/main/MainPage.jsx
  src/pages/search/CategoryPage.jsx
  src/pages/search/CategoryPageStyle.jsx
  src/pages/search/CategorySelect.jsx
  src/pages/search/CategorySelectStyle.jsx
  src/pages/search/SearchModal.jsx
  src/pages/search/SearchModalStyle.jsx
  src/pages/search/SearchPage.jsx
  src/pages/search/SearchPageStyle.jsx
  src/redux/modules/PostSlice.js
Labels: enhancement

#46 Feat/carousel,search/수정
  src/components/carousel/Carousel.jsx
  src/components/carousel/CarouselStyle.jsx
  src/components/carousel/img/BannerIllustOriginal.png
  src/pages/search/SearchModal.jsx
  src/pages/search/SearchModalStyle.jsx
Labels: enhancement

#51 Feat/post
  public/index.html
  src/components/searchMap/SearchMap.jsx
  src/components/searchMap/SearchMapStyle.jsx
  src/hooks/useMultipleInput.js
  src/imgs/upload/Map_LocationMark.png
  src/imgs/upload/Map_MyLocation.png
  src/imgs/upload/Yellow_Marker.png
  src/pages/upload/UploadPage.jsx
  src/pages/upload/UploadPageStyle.jsx
  src/pages/upload/upload/UploadCategory.jsx
  src/pages/upload/upload/searchMap/SearchMapStyle.jsx
  src/pages/upload/upload/searchMap/SearchPartyMap.jsx
  src/pages/upload/upload/searchPartyMap/SearchPartyMap.jsx
  src/pages/upload/upload/searchStoreMap/SearchStoreMap.jsx
  src/pages/upload/upload/stepOne/UploadStepOne.jsx
  src/pages/upload/upload/stepTwo/UploadStepTwo.jsx
  src/pages/upload/upload/stepTwo/currentLocation/CurrentLocation.jsx
  src/pages/upload/upload/stepTwo/toggle/Toggle.jsx
  src/pages/upload/upload/uploadStepOne/UploadStepOne.jsx
  src/pages/upload/upload/uploadStepTwo/UploadStepTwo.jsx
Labels: documentation

#53 Feat/nearby
  .github/ISSUE_TEMPLATE/feature_request.md
  public/index.html
  search (1).svg
  src/components/layout/gnbFloat/GnbFloat.jsx
  src/pages/nearby/NearbyPage.jsx
  src/pages/nearby/kakao/MapContainer.js
  src/pages/nearby/kakao/data.js
  src/shared/router/Router.js
Labels: enhancement

#55 feat: useMultipleInput 수정
  src/components/elements/card/Card.jsx
  src/hooks/useMultipleInput.js
  src/pages/nearby/kakao/MapContainer.js
  src/pages/upload/UploadPage.jsx
  src/pages/upload/upload/stepTwo/UploadStepTwo.jsx
  src/redux/modules/PostSlice.js
Labels: documentation

#56 feat: Card 주석 해제
  src/components/elements/card/Card.jsx
Labels: documentation

#61 Feat/post
  public/index.html
  search (1).svg
  src/components/searchMap/SearchMapStyle.jsx
  src/pages/DetailPage.jsx
  src/pages/detail/CurrentLocation.jsx
  src/pages/detail/CurrentLocationStyle.jsx
  src/pages/detail/CurrentMap.jsx
  src/pages/detail/CurrentMapStyle.jsx
  src/pages/detail/DeleteModal.jsx
  src/pages/detail/DeleteModalStyle.jsx
  src/pages/detail/DetailPage.jsx
  src/pages/detail/DetailPageStyle.jsx
  src/pages/detail/ExitModal.jsx
  src/pages/nearby/NearbyPage.jsx
  src/pages/nearby/kakao/MapContainer.js
  src/pages/nearby/kakao/data.js
  src/pages/search/CategoryPage.jsx
  src/pages/search/SearchPage.jsx
  src/pages/upload/UploadPage.jsx
  src/pages/upload/upload/searchMap/SearchMapStyle.jsx
  src/pages/upload/upload/searchMap/SearchPartyMap.jsx
  src/pages/upload/upload/stepTwo/UploadStepTwo.jsx
  src/pages/upload/upload/stepTwo/currentLocation/CurrentLocation.jsx
  src/redux/modules/PostSlice.js
  src/shared/router/Router.js
Labels: documentation

#63 Feat/mypage/기본css
  src/components/layout/gnbFloat/GnbFloat.jsx
  src/pages/mypage/MyPage.jsx
  src/pages/mypage/MyPageModal.jsx
  src/pages/mypage/MyPageModalStyle.jsx
  src/pages/mypage/MyPageStyle.jsx
  src/shared/router/Router.js
Labels: enhancement
